"""
Locks the Python rule engines to the TypeScript ones.

The frontend keeps a local copy of the clinical logic so the toolkit still
works when the API is unreachable. That fallback is only safe if both
implementations agree exactly — otherwise the guidance a clinician sees would
depend on whether the network happened to be up.

`tests/fixtures/parity.json` is generated by running the TypeScript engines
over their entire input space (`cd frontend && npm run export:parity`). These
tests replay every case through Python and require identical answers.

A failure here means the two implementations have diverged. Fix the divergence
— do not regenerate the fixture to make the test pass.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.services import rules

FIXTURE = Path(__file__).parent / "fixtures" / "parity.json"


@pytest.fixture(scope="module")
def parity() -> dict:
    if not FIXTURE.exists():
        pytest.fail(
            f"{FIXTURE} is missing. Generate it with: "
            "cd frontend && npm run export:parity"
        )
    with FIXTURE.open(encoding="utf-8") as fh:
        return json.load(fh)


def test_fixture_covers_the_whole_uds_input_space(parity):
    """2^8 analytes — anything less means the fixture is stale."""
    assert len(parity["uds"]) == 256


def test_uds_parity(parity):
    mismatches = []
    for case in parity["uds"]:
        result = rules.interpret_uds(case["panel"])
        got = {
            "primary": result["primary"]["id"] if result["primary"] else None,
            "additional": [r["id"] for r in result["additional"]],
            "unaddressed": result["unaddressed"],
        }
        want = {
            "primary": case["primary"],
            "additional": case["additional"],
            "unaddressed": case["unaddressed"],
        }
        if got != want:
            positives = [k for k, v in case["panel"].items() if v] or ["(all negative)"]
            mismatches.append(f"  panel {'+'.join(positives)}: TS={want} PY={got}")

    assert not mismatches, (
        f"{len(mismatches)} of {len(parity['uds'])} UDS panels disagree between "
        "TypeScript and Python:\n" + "\n".join(mismatches[:15])
    )


def test_prescribing_parity(parity):
    mismatches = []
    for case in parity["prescribing"]:
        data = case["input"]
        pathway = rules.evaluate_prescribing(data)
        got = {
            "pathway": pathway["id"] if pathway else None,
            "complete": rules.is_prescribing_complete(data),
            "needsBesmart": rules.needs_besmart(data),
        }
        want = {
            "pathway": case["pathway"],
            "complete": case["complete"],
            "needsBesmart": case["needsBesmart"],
        }
        if got != want:
            mismatches.append(f"  {data}: TS={want} PY={got}")

    assert not mismatches, (
        f"{len(mismatches)} of {len(parity['prescribing'])} prescribing combos "
        "disagree:\n" + "\n".join(mismatches[:15])
    )


def test_induction_parity(parity):
    mismatches = []
    for case in parity["induction"]:
        pathway = rules.find_induction_pathway(case["situation"])
        outcome = rules.select_induction_outcome(pathway, case["answers"])
        complete = pathway is not None and not rules.pending_follow_ups(
            pathway, case["answers"]
        )
        got = {"outcome": outcome["id"] if outcome else None, "complete": complete}
        want = {"outcome": case["outcome"], "complete": case["complete"]}
        if got != want:
            mismatches.append(
                f"  {case['situation']} {case['answers']}: TS={want} PY={got}"
            )

    assert not mismatches, (
        f"{len(mismatches)} of {len(parity['induction'])} induction combos "
        "disagree:\n" + "\n".join(mismatches[:15])
    )
