"""
Loads the reference documents (state guidelines, TennCare BESMART material)
as retrievable chunks.

These are published documents from other organisations, not All4Knox content,
and nothing about them goes through the /review workflow: All4Knox did not
write them and cannot approve them. What All4Knox IS responsible for is the
fidelity of the text it serves, so every chunk says how its text was obtained
(extracted from the PDF text layer, or transcribed from a page image) and, for
transcriptions, whether a person has checked it yet.

The passages themselves are generated by backend/tools/extract_reference.py.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.rag.corpus import Chunk

REFERENCE_DIR = Path(__file__).resolve().parent.parent / "data" / "reference"


@lru_cache
def manifest() -> dict[str, Any]:
    return json.loads((REFERENCE_DIR / "manifest.json").read_text())


def documents(collection: str) -> list[dict[str, Any]]:
    return [d for d in manifest()["documents"] if d["collection"] == collection]


@lru_cache
def passages(document_id: str) -> list[dict[str, Any]]:
    path = REFERENCE_DIR / "passages" / f"{document_id}.json"
    return json.loads(path.read_text())["passages"]


def page_label(start: int, end: int, slides: bool) -> str:
    noun = "slide" if slides else "p."
    if start == end:
        return f"{noun} {start}"
    return f"{'slides' if slides else 'pp.'} {start}–{end}"


def fidelity_note(passage: dict[str, Any]) -> str:
    """How far the served text can be trusted to match the source document."""
    if passage["method"] != "transcribed":
        return "text extracted from the published PDF"
    if passage.get("checkedBy"):
        return (
            f"transcribed from a page image; checked against the source by "
            f"{passage['checkedBy']} on {passage.get('checkedDate') or 'an unrecorded date'}"
        )
    return "transcribed from a page image by an AI model; not yet checked by a person"


def build_chunks(collection: str, authority: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    for doc in documents(collection):
        slides = doc["extraction"] == "slides"
        for p in passages(doc["id"]):
            section = " › ".join(p["section"])
            pages = page_label(p["pageStart"], p["pageEnd"], slides)
            # The heading line is embedded with the body: a question about
            # "benzodiazepine co-prescribing" should match the section named
            # that even when the body text never repeats the phrase.
            text = f"{doc['shortTitle']} — {section} ({pages})\n{p['text']}"
            chunks.append(
                Chunk(
                    id=p["id"],
                    text=text,
                    title=p["section"][-1],
                    module=doc["shortTitle"],
                    # No in-app page renders these documents yet.
                    route="",
                    source_document=doc["title"],
                    source_location=f"{section}, {pages}",
                    slide=p["pageStart"] if slides else None,
                    content_version=doc["edition"],
                    entry_status=doc["documentType"],
                    review_state=fidelity_note(p),
                    collection=collection,
                    authority=authority,
                    issuer=doc["issuer"],
                    published=doc["published"],
                    pages=pages,
                    method=p["method"],
                    currency_note=doc.get("currencyNote"),
                )
            )
    return chunks
